[package]
org = "approach2"
name = "service_1"
version = "0.1.0"
distribution = "2201.9.1"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "approach2"
name = "common_listener"
version = "0.1.0"
repository="local"

