[package]
org = "approach1"
name = "consolidator"
version = "0.1.0"
distribution = "2201.9.1"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "approach1"
name = "service_2"
version = "0.1.0"
repository="local"

[[dependency]]
org = "approach1"
name = "service_1"
version = "0.1.0"
repository="local"

